set(QTE_QT_VERSION "4" CACHE STRING "Qt version to use")

set_property(CACHE QTE_QT_VERSION PROPERTY STRINGS 4 5)

if(NOT (QTE_QT_VERSION VERSION_EQUAL "4" OR QTE_QT_VERSION VERSION_EQUAL "5"))
  message(FATAL_ERROR "Expected value for QTE_QT_VERSION is either '4' or '5'")
endif()

macro(qte_wrap_cpp)
  if(QTE_QT_VERSION VERSION_GREATER "4")
    qt5_wrap_cpp(${ARGN})
  else()
    qt4_wrap_cpp(${ARGN})
  endif()
endmacro()
macro(qte_wrap_ui)
  if(QTE_QT_VERSION VERSION_GREATER "4")
    qt5_wrap_ui(${ARGN})
  else()
    qt4_wrap_ui(${ARGN})
  endif()
endmacro()
macro(qte_add_resources)
  if(QTE_QT_VERSION VERSION_GREATER "4")
    qt5_add_resources(${ARGN})
  else()
    qt4_add_resources(${ARGN})
  endif()
endmacro()
